# Generated by Django 2.2.4 on 2020-03-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='token',
            field=models.CharField(default='', max_length=100, verbose_name='Token'),
        ),
    ]
