# Generated by Django 2.2.4 on 2020-03-29 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_recordmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 5, 2, 0, 615632, tzinfo=utc), primary_key=True, serialize=False, verbose_name='Record Date'),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='note',
            field=models.CharField(default='', max_length=140, verbose_name='Note'),
        ),
    ]
