# Generated by Django 2.2.4 on 2020-03-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200329_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Record Date'),
        ),
    ]
