# Generated by Django 2.2.4 on 2020-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20200329_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Record Date'),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='note',
            field=models.CharField(default='', max_length=140, verbose_name='Note'),
        ),
    ]
