# Generated by Django 2.2.4 on 2020-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20200329_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='date',
            field=models.DateField(verbose_name='Record Date'),
        ),
    ]
