# Generated by Django 2.2.4 on 2020-03-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20200329_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
