# Generated by Django 2.2.4 on 2019-11-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='优惠券',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('优惠券名称', models.CharField(max_length=50, unique=True)),
                ('优惠券折扣', models.DecimalField(decimal_places=2, max_digits=7)),
                ('优惠券介绍', models.TextField()),
            ],
            options={
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.CreateModel(
            name='备注',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('备注类型', models.CharField(choices=[('学生备注', '学生备注'), ('缴费备注', '缴费备注'), ('优惠券备注', '优惠券备注'), ('优惠券使用备注', '优惠券使用备注'), ('家长联系方式备注', '家长联系方式备注'), ('课程备注', '课程备注'), ('班备注', '班备注'), ('班级分配备注', '班级分配备注'), ('老师备注', '老师备注'), ('库存备注', '库存备注'), ('入库记录备注', '入库记录备注'), ('出库记录备注', '出库记录备注')], max_length=10)),
                ('备注关联id', models.IntegerField()),
                ('备注', models.TextField(blank=True)),
                ('备注时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '备注',
            },
        ),
        migrations.CreateModel(
            name='学生',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('学生姓名', models.CharField(max_length=12)),
                ('学生性别', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=12)),
                ('学生生日', models.DateField()),
            ],
            options={
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='库存',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('物品名称', models.CharField(max_length=50)),
                ('物品类别', models.CharField(max_length=30)),
                ('库存数量', models.IntegerField()),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.CreateModel(
            name='班',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('班名称', models.CharField(max_length=50, unique=True)),
                ('上课时间', models.CharField(max_length=50)),
                ('上课教室', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '班',
            },
        ),
        migrations.CreateModel(
            name='老师',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('老师姓名', models.CharField(max_length=12)),
                ('老师电话', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '老师',
            },
        ),
        migrations.CreateModel(
            name='课程',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('课程名称', models.CharField(max_length=50)),
                ('课程定价', models.DecimalField(decimal_places=2, max_digits=7)),
                ('课程介绍', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='课程表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('上课时间', models.DateTimeField()),
                ('下课时间', models.DateTimeField()),
                ('上课教室', models.CharField(max_length=20)),
                ('上课班次', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ray.班')),
            ],
            options={
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='缴费',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('缴费编号', models.CharField(max_length=50, unique=True)),
                ('缴费时间', models.DateTimeField(auto_now_add=True)),
                ('缴费金额', models.DecimalField(decimal_places=2, max_digits=7)),
                ('缴费学生', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.学生')),
                ('缴费项目', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.课程')),
            ],
            options={
                'verbose_name_plural': '缴费',
            },
        ),
        migrations.CreateModel(
            name='班级分配',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('上课日期', models.DateField()),
                ('结课日期', models.DateField()),
                ('学生编号', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ray.学生')),
                ('班编号', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ray.班')),
            ],
            options={
                'verbose_name_plural': '班级分配',
            },
        ),
        migrations.AddField(
            model_name='班',
            name='老师编号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.老师'),
        ),
        migrations.AddField(
            model_name='班',
            name='课程编号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.课程'),
        ),
        migrations.CreateModel(
            name='家长联系方式',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('家长姓名', models.CharField(blank=True, max_length=12)),
                ('联系电话', models.CharField(blank=True, max_length=16)),
                ('与学生关系', models.CharField(blank=True, choices=[('爸爸', '爸爸'), ('妈妈', '妈妈'), ('爷爷', '爷爷'), ('奶奶', '奶奶'), ('姥姥', '姥姥'), ('姥爷', '姥爷'), ('哥哥', '哥哥'), ('姐姐', '姐姐'), ('姑姑', '姑姑'), ('姑父', '姑父'), ('姨', '姨'), ('姨夫', '姨夫'), ('其他直系亲属', '其他直系亲属'), ('其他关系', '其他关系')], max_length=20)),
                ('学生编号', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ray.学生')),
            ],
            options={
                'verbose_name_plural': '家长联系方式',
            },
        ),
        migrations.CreateModel(
            name='出库记录',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('出库时间', models.DateTimeField(auto_now_add=True)),
                ('出库数量', models.IntegerField()),
                ('出库单价', models.DecimalField(decimal_places=2, max_digits=7)),
                ('关联缴费', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ray.缴费')),
                ('出库物品', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.库存')),
            ],
            options={
                'verbose_name_plural': '出库记录',
            },
        ),
        migrations.CreateModel(
            name='入库记录',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('入库时间', models.DateTimeField(auto_now_add=True)),
                ('入库数量', models.IntegerField()),
                ('入库单价', models.DecimalField(decimal_places=2, max_digits=7)),
                ('入库物品', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.库存')),
            ],
            options={
                'verbose_name_plural': '入库记录',
            },
        ),
        migrations.CreateModel(
            name='优惠券使用',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('关联手机号', models.CharField(blank=True, max_length=16)),
                ('优惠券编号', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ray.优惠券')),
                ('缴费单号', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ray.缴费')),
            ],
            options={
                'verbose_name_plural': '优惠券使用',
            },
        ),
    ]
