# Generated by Django 2.2.2 on 2019-06-10 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 16, 15, 13, 46022), verbose_name='Date Published'),
        ),
    ]
